FROM maven:3.6.3-jdk-11

RUN apt-get update

# Install exiftool
RUN apt-get install -y apt-transport-https
RUN apt-get install -y libimage-exiftool-perl
RUN apt-get install -y ffmpeg
RUN apt-get install -y imagemagick


